### PR TITLE
Add support for Google Generative AI (Gemini) embedder

### LINKED ISSUE #2894: [FEAT]: Google Generative AI (Gemini) Embedding Support
### What would you like to see?

Support for the Gemini embedding models

https://ai.google.dev/gemini-api/docs/embeddings

Especially these models:

text-embedding-004
embedding-001

### PR DESCRIPTION
**Pull request by 007900**
### Pull Request Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

### Relevant Issues

resolves #2894 

### What is in this change?

Add support for all Generative AI (Gemini) embedding models

### Developer Validations

- [x] I ran `yarn lint` from the root of the repo & committed changes
- [x] Relevant documentation has been updated
- [x] I have tested my code functionality
- [x] Docker build succeeds locally

### CODE REVIEW

**Comment by spencerthayer** [comment]
Merge this please!

**Review by shatfield4 — APPROVED** [review]
LGTM

**Comment by spencerthayer** [comment]
@timothycarambat when will we see this udpate in the [mintplexlabs/anythingllm:latest](https://hub.docker.com/layers/mintplexlabs/anythingllm/latest/images/sha256-45b426ea4a009b6482f007770d9b14a6dfde1fff4a6b6bfa5b13cff577bacd79) Docker Hub build? Thanks!

**Comment by spencerthayer** [comment]
@timothycarambat okay I see it's updating and it's working. Just to confirm these are the environmental variables for the embedding:

```
# EMBEDDING_ENGINE='gemini'
# GEMINI_EMBEDDING_API_KEY=
# EMBEDDING_MODEL_PREF='text-embedding-004'
```

**Comment by timothycarambat** [comment]
@spencerthayer correct, unlike LLM providers, the embedding keys can be shared, but anytime there is an embedding & LLM provider collision, we will make a second ENV for the API key for that provider so that it doesn't conflict or overwrite the key used for the LLM, in the event the user uses the same provider for LLM + embedder

**Pull request merged**
