### PR TITLE
Support external transcription providers

### LINKED ISSUE #849: [BUG]: MP3 & MP4 upload causes Document Processor to become unavailable
### How are you running AnythingLLM?

Docker (local)

### What happened?

MP3 & MP4 upload causes Document Processor to enter into an infinite loop

On the front end you receive this error message:

> Document Processor Unavailable
> We can't upload your files right now because the document processor is offline. Please try again later.

---

This happens with mp3s & mp4s. Eventually the upload will time out giving an error message.

> Error Uploading File: Fetch Failed

Once the document processor goes offline, no user is able to upload documents.

Once the conversion and/or transcription is complete, the document processor is freed up & the transcription appears available for embedding.

I have done this with the desktop (the .exe), docker (running via onrender) & just running the program via terminal version of Anything LLM.

Running via terminal, a 5 minute audio worked, but if it takes longer than 5 minutes, the error throws a "Failed to fetch".

### Are there known steps to reproduce?

Best as I can tell, just upload an mp3 or mp4 file long enough to timeout the process.

### LINKED ISSUE #850: [FEAT]: Add external transcription providers
### What would you like to see?

Add the ability to use external providers for transcription / file conversion.

For file conversion, cloudconvert is relatively easy to use, cheat & has an API

Same with Deepgram for transcriptions.

### PR DESCRIPTION
**Pull request by timothycarambat**
### Pull Request Type

- [x] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

### Relevant Issues

resolves #850
resolves #849

### What is in this change?

Supports OpenAI whisper along-side as an additional configuration option to allow quicker transcription of files (mp3, mp4, etc) - 25MB LIMIT!

The localWhisper model still can run if needed but it often crashes instances when on underpowered devices with restricted RAM or CPU. OpenAI is a quick way to resolve this and satisfy the user need.

### Developer Validations

- [x] I ran `yarn lint` from the root of the repo & committed changes
- [x] Relevant documentation has been updated
- [x] I have tested my code functionality
- [x] Docker build succeeds locally

### CODE REVIEW

**Comment by timothycarambat** [comment]
This sets up the ability for us to add speech-to-text chatting with workspace 👍

**Comment by AIbottesting** [comment]
Anything-LLM is awesome! Thank you and your team for all your hard work and passion. Because I am visually impaired, my only feature request is a text-to-speech button to read AI output. I currently copy and paste every single time into eSpeak which uses Microsoft Windows 10 built-in text-to-speech engine. This is my humble wish. However, if I could dream, being able to press a button for speech-to-text and be able to have a two-way conversation would be out of this world. Furthermore, could you imagine being able to scan a paper receipt and Anything-LLM puts the data into an Excel file for you! Wow

**Comment by timothycarambat** [comment]
@AIbottesting thank you for raising this. I think we can easily support TTS using the built-in browser TTS. I am sorry we overlooked that kind of accessibility feature. Please let me know if you have any further accessibility issues and we will try to get those handled

**Comment by AIbottesting** [comment]
Thank you for being kind and no need to be sorry. On a side note, the government (Department of Rehabilitation) spends money on my behalf for a software called Kurzweil 3000 to read my college texts. I think this software is used by many disabled people at their jobs. I also believe software companies go through some kind of accessibility certification which may help your business side to be able to claim you are compliant. Just a thought. Keep on kicking butt as you do.

**Pull request merged**
