### PR TITLE
refactor: convert chunk embedding to one API call

### PR DESCRIPTION
**Pull request by jwaltz**
I was having really long embed times for a couple large .docx documents ingested through the `/hotdir`. One had 256 chunks and took many minutes to fully embed, sometimes never finishing at all.

I converted the `embedChunk()` method to accept a list of chunks instead of just one chunk, and make a single call to OpenAI's embedding API endpoint, which seems to have sped up the embed process dramatically. The refactored `embedChunks()` required some changes to its usage in `addDocumentToNamespace()` as well. I included these changes for the 3 vector db options at `/server/utils/vectorDbProviders/[vectorDb]/index.js`

Let me know what you think and if this is helpful. Again, apologies for my editor's lsp changing some of the method signatures and line-length formatting, hope it is ok.

### CODE REVIEW

**Comment by timothycarambat** [comment]
LFG - will review. Thank you!

**Comment by jwaltz** [comment]
@timothycarambat no problem, linted and committed.

**Comment by AntonioCiolino** [comment]
is there a reason this isn't merges (other than merge conflicts)? Anything that could enhance speed would be helpful.

**Comment by timothycarambat** [comment]
Moved to #153

**Pull request closed without merging**
