### PR TITLE
Improve RAG responses via source backfilling

### LINKED ISSUE #1240: [CHORE]: Improve RAG retention via history context
### What would you like to see?

When we send a chat like `What is AnythingLLM` the system will find relevant context, if any and append it under the system prompt.
```shell
{SYSTEM}
<context>
<context>
# No history
<user prompt>
```

However, on follow up request, where we may not get a vector search result due to ambiguity like `tell me some features`
We will get a flow like

```shell
{SYSTEM}
# NO CONTEXT!
<reply from prompt 1 from LLM>
<user prompt>
```

This puts 100% of the response result on the `<reply from prompt 1 from LLM>` response where we could leverage the previous citations in the history to help offload the responsibility and scope of the answering.

### PR DESCRIPTION
**Pull request by timothycarambat**
resolves #1240
 
 ### Pull Request Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [x] 🔨 chore
- [ ] 📝 docs

> [!WARNING]
> This PR enables `query` to work with chat history now but **only** in the app. Behavior in the embed is the same.

In an effort to improve RAG results without adding unwarranted or "conditional" middleware like ReRankers, there is a lot of room for improvement of the traditional RAG pipeline AnythingLLM uses. This PR includes the ability to **backfill** sources during a chat session.

## What is backfilling?

Currently, AnythingLLM will append `Context` snippets to the `system` prompt on each chat. These contexts come from the attached VectorStores `.similaritySearch` method. While this works for direct questions this does not scale well as chat's become higher context or more vague. This leads to a bad RAG experience in a traditional chat, but is far worse in `query` where a follow-up query, that is contextually relevant, is deemed irrelevant.

## Example

**prompt 1**: "What is anythingllm?" 
-  possibly get 4 good sources and get a good LLM response as it is operating with high context.

**prompt 2**: "Tell me some features" 
  - This question is appropriate, topical, and a decent inquiry but standalone is quite vague when viewed outside of the context of the chat.
  - Possible get 0 - 1 maybe relevant sources
  - We now must rely on the _maybe_ existent snippet for source and hope the previous LLM response has something worth looking at

_introduced in this pr_

**prompt 1**: "What is anythingllm?" 
-  possibly get 4 good sources and get a good LLM response as it is operating with high context.

**prompt 2**: "Tell me some features" 
  - Possible get 0 - 1 maybe relevant sources
  - We now can backfill the context window in this order of priority
     - Pinned documents
     - This queries search results
     - Work backwards in chat history citations to backfill the source window to the workspace's assigned snippet window value.
 
 
 With this, we can now ensure that follow-up questions will be more relevant and contextually pertinent as a conversation continues. 
 
 **"What if the contextual topic changes"?**
 - This is handled as we prioritize sources from search results  first, then backfill in by more recent chats with historical references
 - If you have a relevant contextual change in the chat, those sources will take precedence over the historical ones and will become the new historical reference

### CODE REVIEW

**Comment by shatfield4** [comment]
LGTM

**Comment by Propheticus** [comment]
Pulled latest docker image. Chat in query mode, looks like it works:
image
As designed no citations are shown (because no hits on last query), but still an answer is given based on earlier context in the conversation. 💯 

(also confirmed by checking LM Studio logs)

**Comment by DangerousBerries** [comment]
> Pulled latest docker image. Chat in query mode, looks like it works: image As designed no citations are shown (because no hits on last query), but still an answer is given based on earlier context in the conversation. 💯
> 
> (also confirmed by checking LM Studio logs)

Huh, I thought all this time that only the last message mattered. Why is it not showing the citations for Context snippets?

**Comment by DangerousBerries** [comment]
Is there a way to see what Context snippets are added to the system prompt?

**Pull request merged**
