### PR TITLE
Implement support for HuggingFace Inference Endpoints

### LINKED ISSUE #679: [FEAT]: HuggingFace Inference Endpoint
### What would you like to see?

Add support for the 150,000 models found on HuggingFace that are available for inferencing and text/conversation generation.

https://huggingface.co/docs/text-generation-inference/messages_api#streaming

### PR DESCRIPTION
**Pull request by timothycarambat**
### Pull Request Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

### Relevant Issues

resolves #679

### What is in this change?

Adds support for Hugging Faces dedicated inference endpoints for LLM Selection

### Additional Information

We may need to build some documentation on how to set up a dedicate endpoint so that chats can be sent as it may not be obvious to a layperson. Anyone using HuggingFace should understand the requirements though as the defaults for a new endpoint do work.

### Developer Validations

- [x] I ran `yarn lint` from the root of the repo & committed changes
- [x] Relevant documentation has been updated
- [x] I have tested my code functionality
- [x] Docker build succeeds locally

### CODE REVIEW

**Comment by ognjenAct** [comment]
hi guys, first I would like to thank you for all your efforts 🏆

And regarding this PR, for HF support, I always have 422 error when I try to connect anything-llm to HF TGI 

Any hint?

**Comment by timothycarambat** [comment]
What model are you using? Not all of them can support chat and may be missing a template to support chat via the HF TGI endpoint

**Comment by ognjenAct** [comment]
Hi there, tnx for re

sorry I wasn't precise, I'm trying with this one:
https://huggingface.co/mistralai/Mistral-7B-v0.1

But you made a good point, maybe I can try with another one 

I will update you

**Comment by ognjenAct** [comment]
Update:
I've tried with llama2 7b Model, same 422 : /
https://huggingface.co/meta-llama/Llama-2-7b-chat-hf

From cURL all good, python client all good 

I'm here if I can help you, share more info etc

**Comment by timothycarambat** [comment]
Can you paste in the cURL request you are using? _Please remove the key!_
We are using the openai library and message format and passing `tgi` as the model to the endpoint- which is what their docs outline?

Testing an endpoint right now with [OpenHermes](TheBloke/OpenHermes-2.5-Mistral-7B-GPTQ) on an A10G
Screenshot 2024-02-20 at 1 35 13 PM
Screenshot 2024-02-20 at 1 35 17 PM

Screenshot 2024-02-20 at 1 36 15 PM

Getting 422 as well - going to open issue as this appears to be new

**Comment by ognjenAct** [comment]
here you go

`curl "https://jbtstsr7thraha6.eu-west-1.aws.endpoints.huggingface.cloud" \
-X POST \
-H "Accept: application/json" \
-H "Authorization: hf_***" \
-H "Content-Type: application/json" \
-d '{
    "inputs": "Can you please let us know more details about your ",
    "parameters": {}
}'`

ps 
I think openai lib is messing with format of req (body of req to be accurate) but I'm not sure ...

**Comment by timothycarambat** [comment]
I think this has to do with the model missing a chat_template file. It seems that for inferencing using TGI this must exist for the model. Will look into this since we cannot just run arbitrary chat completion if the inference endpoint does not automatically templatize the input using the inference API

**Comment by timothycarambat** [comment]
Hm, interesting. This model works out of the box: https://huggingface.co/teknium/OpenHermes-2.5-Mistral-7B

So this must be some kind of compatibility thing for models to support chat/message formatting?

**Comment by ognjenAct** [comment]
hmm interesting, I’m gonna try it out with that model…. btw maybe worthy to look on this and trying to implement for HF part of the app:
   https://huggingface.co/docs/huggingface.js/en/inference/README

**Comment by ognjenAct** [comment]
about this point:
"So this must be some kind of compatibility thing for models to support chat/message formatting?"

I've noticed for example for Mistral 7b model, this is part of body req:
`query({
    "inputs": "Can you please let us know more details about your ",
    "parameters": {}
}).then((response) => {
	console.log(JSON.stringify(response));
});`
notice that is using `input` as param

And for [Op](https://huggingface.co/teknium/OpenHermes-2.5-Mistral-7B)
it is different,  it is content as param that is part of body req:

`messages = [
    {"role": "system", "content": "You are Hermes 2."},
    {"role": "user", "content": "Hello, who are you?"}
]`
So maybe this can help you ...

Cheers

**Pull request merged**
