### PR TITLE
Customize refusal response for `query` mode

### LINKED ISSUE #1197: [FEAT]: change deafult answer
### What would you like to see?

How to change default answer, "There is no relevant information in this workspace to answer your query."?

### PR DESCRIPTION
**Pull request by timothycarambat**
### Pull Request Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

### Relevant Issues

resolves #1197

### What is in this change?

Add refusal response customization to stream, API chat, and embed chat in the workspace setting.

### Developer Validations

- [x] I ran `yarn lint` from the root of the repo & committed changes
- [x] Relevant documentation has been updated
- [x] I have tested my code functionality
- [x] Docker build succeeds locally

### CODE REVIEW

**Comment by timothycarambat** [comment]
Screenshot 2024-04-30 at 4 11 29 PM

In workspace settings

**Comment by santini-cyber** [comment]
Did this PR merge also include functionality which inhibits the refusal responses from being written to the local database?  Query mode refusal responses are no longer being captured in Workspace chats in my latest build from 5/29/24.

**Comment by timothycarambat** [comment]
Refusal chats were never logged and the PR did not change that. If you got a refusal that was logged as a chat, it came from the LLM itself

**Comment by santini-cyber** [comment]
I usually role our DE to a current build every 4-5 weeks.  I was slacking last month and waited six weeks. I am running a April 16th build and a May 30th build.  Embedded docs are the same, workspace configuration is identical.  Using query mode in both. Prompts are identical.  However, I am getting a different "response" or observed behavior.  I am using the same LLM version so I don't think it is a difference there.  The observed behavioral difference is that the prompts which don't result in a citation are captured in the April 16th build but not in the May 30th build. Should I open a bug and provide a more detailed description?

**Pull request merged**
