### PR TITLE
brief description of and guidance for running AnythingLLM on runtipi

### PR DESCRIPTION
**Pull request by cori**
### Pull Request Type

- [x] ✨ feat
_maybe?_
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [x] 📝 docs
probably more likely this

### Relevant Issues

I did not create an issue, but I can if that would be useful.

### What is in this change?

Adds two paragraphs of guidance for running Dockerized AnythingLLM on [runtipi](https://runtipi.io), an "easy-to-use" home server orchestrator

### Additional Information

This is awaiting this [PR](https://github.com/runtipi/runtipi-appstore/pull/4430) to be merged, which may take some time (and may end up not happening ;-) ). I'll draft it once created so that's clear.

### Developer Validations

- [x] I ran `yarn lint` from the root of the repo & committed changes
i ran it and it came back with an unrelated in server/endpoints/workspaces.js, which i am not including
- [x] Relevant documentation has been updated
- [x] I have tested my code functionality
I am running AnythingLLM in runtipi and have been for some time. I've also been through the install and onboarding numerous times :-P
- [x] Docker build succeeds locally
no changes here

There's an open [PR](https://github.com/runtipi/runtipi-appstore/pull/4430) on the runtipi appstore that adds AnythingLLM as a one-click install. Once merged these changes to add runtipi as a one-click install become _relevant_. Hopefully they will also be _desireable_.

Happy to make any changes over there that would make this process more clear. Also totes understand if putting this into the official docs isn't of interest.

### CODE REVIEW

**Comment by cori** [comment]
BTW thanks for moving to tagged images - that made this public addition to runtipi make sense (otherwise i've been running it from a "[custom app store](https://runtipi.io/docs/contributing/running-locally#using-your-own-appstore-repository)" of [my own](https://github.com/cori/runtipi-appstore), but didn't seem ready for the public store).

**Comment by timothycarambat** [comment]
This should be placed _somewhere_ but in the documentation repo. This markdown doc should not try to market alternatives (even if easier) because inevitably we wind up responsible for questions around these integrations and we are not the official maintainers of that integration.

Alternatively, you can make a folder and place documentation & supported instructions in the `cloud-deployments` folder -since that is all unofficial community-owner integrations.

**Comment by cori** [comment]
Excellent thanks! I’ll move it to a more appropriate spot.

**Comment by timothycarambat** [comment]
Closing till ready for re-review 👍

**Comment by cori** [comment]
there's a bit of a backlog few new app PRs so it may be a few. I also noticed AnythingLLM available on CasaOS so i may add a doc for that in `cloud-deployments` as well.

**Pull request closed without merging**
