### PR TITLE
[FEAT]: Possibility to "white label" meta information

### LINKED ISSUE #1256: [FEAT]: "White label" possibility
### What would you like to see?

An option to white label an ALLM instance:

1. Remove ALLM references on login screen (instead using the custom logo)
2. Remove ALLM buttons on the bottom of the workspace field

### LINKED ISSUE #1373: [FEAT]: Possibility to "white label" meta information
### What would you like to see?

Possibility to adjust the meta information showing in a browser when accessing an instance.
I guess this is the part that would need to be amended to show custom information.

image

### PR DESCRIPTION
**Pull request by doumencp**
### Pull Request Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

### Relevant Issues

resolves #1373 (except the related closed #1256 that should be another issue)

### What is in this change?

Enables possibility to while label metadatas.

### Additional Information

Everything works just fine.

### Developer Validations

- [x] I ran `yarn lint` from the root of the repo & committed changes
- [x] Relevant documentation has been updated
- [x] I have tested my code functionality
- [x] Docker build succeeds locally

### CODE REVIEW

**Comment by timothycarambat** [comment]
From the current WIP - this breaks the share image and content when the website is shared as a link in most application since the content would need to render first for the new tab content to show

**Comment by doumencp** [comment]
> From the current WIP - this breaks the share image and content when the website is shared as a link in most application since the content would need to render first for the new tab content to show

Fair enough. Didn't think it would behave like this.  Does the share feature only relie on `<meta>` tag ? If it's the case, it would mean i still can set the `<title>` and `<link>` as dynamic to custom the visual part. Wht do you think ?

**Comment by timothycarambat** [comment]
In specific these tags render the share card and image stuff
```
  <title>AnythingLLM | Your personal LLM trained on anything</title>

  <meta name="title" content="AnythingLLM | Your personal LLM trained on anything">
  <meta name="description" content="AnythingLLM | Your personal LLM trained on anything">

  <!-- Facebook -->
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://useanything.com">
  <meta property="og:title" content="AnythingLLM | Your personal LLM trained on anything">
  <meta property="og:description" content="AnythingLLM | Your personal LLM trained on anything">
  <meta property="og:image"
    content="https://raw.githubusercontent.com/Mintplex-Labs/anything-llm/master/images/promo.png">

  <!-- Twitter -->
  <meta property="twitter:card" content="summary_large_image">
  <meta property="twitter:url" content="https://useanything.com">
  <meta property="twitter:title" content="AnythingLLM | Your personal LLM trained on anything">
  <meta property="twitter:description" content="AnythingLLM | Your personal LLM trained on anything">
  <meta property="twitter:image"
    content="https://raw.githubusercontent.com/Mintplex-Labs/anything-llm/master/images/promo.png">
 ```
 
 The reason this issue has not been done yet is that basically the root content header needs to be server-side rendered because link preview will not run client-side JS (which this code currently does correctly right now!) so what happens is when you visit the page in browser the tab and content look OK, but that all goes away when the link is pasted into a DM, Slack message, etc - anywhere link previews are supported

**Comment by doumencp** [comment]
Alright, i figured out another way to achieve this customization (overwrite the index.html with a custom one inside the container), i'll go with that for the moment. Closing the PR.

**Comment by timothycarambat** [comment]
@doumencp I can look into this as well. I think just serves the index.html from the server `/` in production mode will allow a rewrite of the header objects and since on the server side we have the DB - we can query + serve and cache it for faster page responses

**Pull request closed without merging**
